image: registry.gitlab.com/qsantos/orbit/ci

test-and-build:
  script:
    # Linting
    - cppcheck --suppress=missingIncludeSystem --suppress=noExplicitConstructor --error-exitcode=1 --quiet --enable=all *.h *.c *.hpp *.cpp
    # Tests
    - make test
    - ./test
    # Linux GUI
    - make linux
    - make destroy
    # Windows GUI
    - make windows
    - make destroy
  artifacts:
    paths:
    - "*.tgz"
    - "*.zip"
    expire_in: 1 week
