image: registry.gitlab.com/qsantos/orbit/ci

test:
  script:
    - cppcheck --suppress=missingIncludeSystem --suppress=noExplicitConstructor --error-exitcode=1 --quiet --enable=all *.h *.c *.hpp *.cpp
    - make test clean
    - ./test
