image: registry.gitlab.com/qsantos/orbit/ci

test-and-build:
  script:
    # Linting
    - cppcheck --suppress=missingIncludeSystem --suppress=noExplicitConstructor --error-exitcode=1 --quiet --enable=all *.h *.c *.hpp *.cpp
    # Tests
    - make test
    - ./test
    # Linux GUI
    - make linux
    - make destroy
    # Windows GUI
    - cp /usr/lib/gcc/x86_64-w64-mingw32/8.3-win32/{libgcc_s_seh-1.dll,libstdc++-6.dll,libssp-0.dll} .
    - cp /opt/dlls/* .
    - make windows
    - make destroy
  artifacts:
    paths:
    - "*.tgz"
    - "*.zip"
    expire_in: 1 week
