image: registry.gitlab.com/qsantos/orbit/ci

test-and-build:
  script:
    # Linting
    - cppcheck --suppress=missingIncludeSystem --suppress=noExplicitConstructor --error-exitcode=1 --quiet --enable=all *.h *.c *.hpp *.cpp
    # Tests
    - make test
    - ./test
    # Linux GUI
    - make gui
    - tar zcvf orbit-lin64.tgz gui data/
    - make destroy
    # Windows GUI
    - PLATFORM=win32 make gui
    - zip -r orbit-win64.zip gui.exe *.dll data/
    - make destroy
  artifacts:
    paths:
    - orbit-lin64.tgz
    - orbit-win64.zip
    expire_in: 1 week
