#!/usr/bin/env bash
# Exit at first error
set -e

# syntax check
#   .-- lint mode: only parse, treat any warning as an error
#   v
gcc -fsyntax-only -Werror -Wall -Wextra -Wpedantic -Wconversion -Wshadow -Wvla "$@"
#   ^
#   `-- usual paranoid options

# static analysis
#        .-- disable lookup for system includes
#        v
cppcheck --suppress=missingIncludeSystem --suppress=noExplicitConstructor \
    --enable=warning,style,performance,portability,unusedFunction,missingInclude \
    --error-exitcode=1 --quiet "${CPPCHECK_FLAGS}" "$@"
