#!/usr/bin/env bash
# Exit at first error
set -e

# syntax check
#   .-- lint mode: only parse, treat any warning as an error
#   v
gcc -fsyntax-only -Werror -Wall -Wextra -Wpedantic -Wconversion -Wshadow -Wvla "$@"
#   ^
#   `-- usual paranoid options

# static analysis
#        .-- disable lookup for system includes
#        v
cppcheck --suppress=missingIncludeSystem --suppress=noExplicitConstructor --error-exitcode=1 --quiet --enable=all \
    --suppress=unusedFunction "$@"
#   ^
#   `-- partial linting causes false positives
