#!/usr/bin/env bash
# Usage: copy this file to .git/hooks/

# Exit at first error
set -e

# To handle partially committed files, we must copy the staged changes to a
# separate location
# See also https://stackoverflow.com/a/36793330
TEMPDIR=$(mktemp -d)
trap "rm -rf $TEMPDIR" EXIT SIGHUP SIGINT SIGQUIT SIGTERM
git checkout-index --prefix=$TEMPDIR/ -af

export CPPCHECK_FLAGS="--suppress=unusedFunction"

git diff --cached --name-only --diff-filter=AM |  # list modified files
    grep -e '\.[hc]$' -e '\.[hc]pp$' |  # filter C/C++ files
    (cd $TEMPDIR  # lint the committed files from the temporary directory
    xargs --no-run-if-empty ./lint
)
